language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip -r requirements.txt"
# command to run tests
script: "python test.py"
# disable notification emails
notifications:
email: false